#!/bin/sh

BAT_PATH=/sys/class/power_supply/BAT0

STATUS=$(cat $BAT_PATH/status)
CHARGE_NOW=$(cat $BAT_PATH/charge_now)
CHARGE_FULL=$(cat $BAT_PATH/charge_full)
BAT=$(( CHARGE_NOW * 100 / CHARGE_FULL ))%

if [ "$STATUS" = "Charging" ]; then
	echo "<span size=\"large\">󰂄</span> $BAT"
	exit 0
elif [ "$STATUS" != "Discharging" ] && [ "$STATUS" != "Not charging" ]; then
	echo "BAT ERROR: $STATUS"
	exit 33
elif [ ${BAT%?} -le 30 ]; then
	icon="󰁼"
elif [ ${BAT%?} -le 60 ]; then
	icon="󰁾"
elif [ ${BAT%?} -le 90 ]; then
	icon="󰂀"
else
	icon="󰁹"
fi

echo "<span size=\"large\">$icon</span> $BAT"

[[ ${BAT%?} -le 15 ]] && exit 33 || exit 0
