[theme]
theme = "solarized-dark"

[icons]
icons = "awesome4"


# REMINDERS

[[block]]
block = "custom"
json = true
command = '''echo "{\"state\":\"Critical\", \"text\":\"`test -f ~/.remind/meds && echo meds`\"}" '''
interval = 10
hide_when_empty = true
signal = 2
[[block.click]]
button = "left"
cmd = "rm ~/.remind/meds && pkill -SIGRTMIN+2 i3status-rs"

[[block]]
block = "custom"
json = true
command = '''echo "{\"state\":\"Critical\", \"text\":\"`test -f ~/.remind/todo && echo todo`\"}" '''
interval = 10
hide_when_empty = true
signal = 2
[[block.click]]
button = "left"
cmd = "rm ~/.remind/todo && pkill -SIGRTMIN+2 i3status-rs"


#[[block]]
#block = "music"
#format = " $icon {$combo.str(max_w:20,rot_interval:0.5) |}"
#[[block.click]]
#button = "left"
#action = "play_pause"


# SMO.wiki STATUS

[[block]]
block = "custom"
json = true
command = ''' echo "{\"icon\":\"ping\",\"text\":\"smo.wiki: `ping -c1 smo.wiki | tail -n1 | cut -d'/' -f5`ms (`curl -I https://smo.wiki/Home | head -n1 | cut -d' ' -f2`)\"}" '''
interval = 60


# OTHER

[[block]]
block = "uptime"
interval = 1

[[block]]
block = "custom"
command = ''' echo "{\"icon\": \"keyboard\", \"text\": \" `getxkblayout -s`\"}" '''
signal = 1
json = true

[[block]]
block = "battery"
driver = "upower"
device = "hidpp_battery_0"
format = " $icon  kb $percentage "
interval = 10

[[block]]
block = "pomodoro"
notify_cmd = "notify-send '{msg}'"
blocking_cmd = false

[[block]]
block = "sound"
max_vol = 100

[[block]]
block = "time"
interval = 1
timezone = ["Europe/Dublin", "Asia/Tokyo", "Australia/Melbourne", "US/Pacific", "US/Mountain", "US/Central", "US/Eastern", "Atlantic/Reykjavik"]
format = "$icon $timestamp.datetime(f:'%a %F %T %Z', l:is_IS) "
[[block.click]]
button = "down"
action = "next_timezone"
[[block.click]]
button = "up"
action = "prev_timezone"
